{"uid":"497784b09a77138a","name":"test_negative_login_form","fullName":"tests.test_login_page.TestLoginForm#test_negative_login_form","historyId":"a4a2b822388e0e770f0cfa5d076f82fc","time":{"start":1689186456361,"stop":1689186456361,"duration":0},"description":"В данном тесте, воспроизводится сценарий при котором:         1.пользователь при аутентификации, указывает невалидные данные         2.сообщение об ошибке(алерт) не появляется         3.система принимает данные и авторизует пользователя","descriptionHtml":"<p>В данном тесте, воспроизводится сценарий при котором:         1.пользователь при аутентификации, указывает невалидные данные         2.сообщение об ошибке(алерт) не появляется         3.система принимает данные и авторизует пользователя</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562381a714e3 <unknown>\n#1 0x5623817a0c76 <unknown>\n#2 0x5623817c9d78 <unknown>\n#3 0x5623817c6029 <unknown>\n#4 0x562381804ccc <unknown>\n#5 0x56238180447f <unknown>\n#6 0x5623817fbde3 <unknown>\n#7 0x5623817d12dd <unknown>\n#8 0x5623817d234e <unknown>\n#9 0x562381a313e4 <unknown>\n#10 0x562381a353d7 <unknown>\n#11 0x562381a3fb20 <unknown>\n#12 0x562381a36023 <unknown>\n#13 0x562381a041aa <unknown>\n#14 0x562381a5a6b8 <unknown>\n#15 0x562381a5a847 <unknown>\n#16 0x562381a6a243 <unknown>\n#17 0x7fb385d3ab43 <unknown>","statusTrace":"E   selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n      (unknown error: DevToolsActivePort file doesn't exist)\n      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n    Stacktrace:\n    #0 0x562381a714e3 <unknown>\n    #1 0x5623817a0c76 <unknown>\n    #2 0x5623817c9d78 <unknown>\n    #3 0x5623817c6029 <unknown>\n    #4 0x562381804ccc <unknown>\n    #5 0x56238180447f <unknown>\n    #6 0x5623817fbde3 <unknown>\n    #7 0x5623817d12dd <unknown>\n    #8 0x5623817d234e <unknown>\n    #9 0x562381a313e4 <unknown>\n    #10 0x562381a353d7 <unknown>\n    #11 0x562381a3fb20 <unknown>\n    #12 0x562381a36023 <unknown>\n    #13 0x562381a041aa <unknown>\n    #14 0x562381a5a6b8 <unknown>\n    #15 0x562381a5a847 <unknown>\n    #16 0x562381a6a243 <unknown>\n    #17 0x7fb385d3ab43 <unknown>","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser","time":{"start":1689186456362,"stop":1689186457026,"duration":664},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562381a714e3 <unknown>\n#1 0x5623817a0c76 <unknown>\n#2 0x5623817c9d78 <unknown>\n#3 0x5623817c6029 <unknown>\n#4 0x562381804ccc <unknown>\n#5 0x56238180447f <unknown>\n#6 0x5623817fbde3 <unknown>\n#7 0x5623817d12dd <unknown>\n#8 0x5623817d234e <unknown>\n#9 0x562381a313e4 <unknown>\n#10 0x562381a353d7 <unknown>\n#11 0x562381a3fb20 <unknown>\n#12 0x562381a36023 <unknown>\n#13 0x562381a041aa <unknown>\n#14 0x562381a5a6b8 <unknown>\n#15 0x562381a5a847 <unknown>\n#16 0x562381a6a243 <unknown>\n#17 0x7fb385d3ab43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/testing_foodgram_project_react/testing_foodgram_project_react/conftest.py\", line 26, in browser\n    browser = webdriver.Chrome(\n              ^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 84, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 104, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 378, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"feature","value":"Тесты аутентификации зарегистрированного пользователя."},{"name":"story","value":"Негативный тест: Тест аутентификации                  с невалидными данными."},{"name":"tag","value":"negative_login_form(scope='function')"},{"name":"tag","value":"login_form_test(scope='class')"},{"name":"tag","value":"run(order=2)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login_page"},{"name":"subSuite","value":"TestLoginForm"},{"name":"host","value":"fv-az256-210"},{"name":"thread","value":"2518-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login_page"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["login_form_test(scope='class')","run(order=2)","negative_login_form(scope='function')"]},"source":"497784b09a77138a.json","parameterValues":[]}